apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: ecomm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
          volumeMounts:
            - name: datasource-config
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboard-provider-config
              mountPath: /etc/grafana/provisioning/dashboards
            - name: dashboard-jvm
              mountPath: /var/lib/grafana/dashboards/jvm
            - name: dashboard-kafka
              mountPath: /var/lib/grafana/dashboards/kafka
            - name: dashboard-sboot3
              mountPath: /var/lib/grafana/dashboards/sboot3
            - name: dashboard-autoscaling
              mountPath: /var/lib/grafana/dashboards/autoscaling
      volumes:
        - name: datasource-config
          configMap:
            name: grafana-datasource-config
        - name: dashboard-provider-config
          configMap:
            name: grafana-dashboard-provider-config
        - name: dashboard-jvm
          configMap:
            name: grafana-dashboard-jvm
        - name: dashboard-kafka
          configMap:
            name: grafana-dashboard-kafka
        - name: dashboard-sboot3
          configMap:
            name: grafana-dashboard-sboot3
        - name: dashboard-autoscaling
          configMap:
            name: grafana-dashboard-autoscaling

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: ecomm
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: NodePort