apiVersion: v1
kind: ServiceAccount
metadata:
  name: load-metrics-collector
  namespace: ecomm
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: load-metrics-collector
  namespace: ecomm
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["keda.sh"]
    resources: ["scaledobjects"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: load-metrics-collector
  namespace: ecomm
subjects:
  - kind: ServiceAccount
    name: load-metrics-collector
    namespace: ecomm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: load-metrics-collector
