apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator-deployment
  labels:
    app: coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
        - name: coordinator
          image: siddhesh1712/coordinator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service.ecomm.svc.cluster.local:9092"
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              value: "http://jaeger-service.ecomm.svc.cluster.local:4318/v1/traces"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"


---
apiVersion: v1
kind: Service
metadata:
  name: coordinator-service
spec:
  selector:
    app: coordinator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: NodePort