apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: siddhesh1712/order:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka-service.ecomm.svc.cluster.local:9092"
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              value: "http://jaeger-service.ecomm.svc.cluster.local:4318/v1/traces"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: org.hibernate.dialect.PostgreSQLDialect
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: none
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service.ecomm.svc.cluster.local:5432/order_db"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"


---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: ClusterIP